version: '3.1'

services:
  web:
    image: promountweb
    build:
      context: PromountApp/PromountApp.Api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
    env_file:
      - .env
    networks:
      - mynetwork
      
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: promountDB
    ports:
      - "5432:5432"
    networks:
      - mynetwork
        
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge