services:
  web:
    image: promountweb
    build:
      context: PromountApp/PromountApp.Api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "80:8080"
    env_file:
      - .env
    networks:
      - mynetwork
      
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: promountDB
    ports:
      - "5432:5432"
    networks:
      - mynetwork
      
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redisdata:/data
    environment:
      REDIS_URL: redis:6379
    ports:
      - "6379:6379"
    networks:
      - mynetwork
        
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    depends_on:
      - prometheus
      - jaeger
      - elasticsearch
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mynetwork
        
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - mynetwork

  jaeger:
    restart: always
    image: jaegertracing/all-in-one:latest
    depends_on:
      - elasticsearch
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    networks:
      - mynetwork
    ports:
      - "4317:4317"
      - "16686:16686"
      - "4318:4318"

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.4
    environment:
      - discovery.type=single-node
    volumes:
      - ./grafana:/usr/share/elasticsearch/data
      - ./elasticsearch/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - mynetwork
    ports:
      - "9200:9200"

networks:
  mynetwork:
    driver: bridge